const Actions = {
    INIT_DATA_FETCHING: "INIT_DATA_FETCHING",
    SET_GRID_DATA: "SET_GRID_DATA",
    SHOW_DELETE_RECORD_MODAL: "SHOW_DELETE_RECORD_MODAL",
    HIDE_DELETE_RECORD_MODAL: "HIDE_DELETE_RECORD_MODAL",
    SHOW_ADD_NEW_RECORD: "SHOW_ADD_NEW_RECORD",
    SHOW_EDIT_RECORD: "SHOW_EDIT_RECORD",
    HIDE_EDIT_RECORD_VIEW: "HIDE_EDIT_RECORD_VIEW",
    HANDLE_EDIT_RECORD_VALUE_CHANGE: "editRecord/HANDLE_VALUE_CHANGE",
    SAVE_RECORD: "editRecord/SAVE_RECORD",
    LOADING_FINISHED: "editRecord/LOADING_FINISHED",
    SAVE_RECORD_ERROR: "editRecord/SAVE_RECORD_ERROR",
    SAVE_RECORD_SUCCESS: "editRecord/SAVE_RECORD_SUCCESS"
}

export default Actions;